# Generated by Django 5.0.10 on 2024-12-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementData', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDemographics',
        ),
    ]
