# Generated by Django 5.0.10 on 2024-12-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementData', '0003_customerdemographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGeography',
            fields=[
                ('BusinessEntityID', models.IntegerField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=30)),
                ('StateProvinceName', models.CharField(max_length=50)),
                ('PostalCode', models.CharField(max_length=15)),
                ('CountryRegionName', models.CharField(max_length=50)),
            ],
        ),
    ]
