# Generated by Django 5.0.10 on 2024-12-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementData', '0004_customergeography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facttable',
            name='CustomerDemographicsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementData.customerdemographics'),
        ),
        migrations.AlterField(
            model_name='facttable',
            name='CustomerGeographyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementData.customergeography'),
        ),
    ]
