# Generated by Django 5.0.10 on 2024-12-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementData', '0005_alter_facttable_customerdemographicsid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdemographics',
            old_name='BusinessEntityID',
            new_name='CustomerDemographicsID',
        ),
        migrations.RenameField(
            model_name='customergeography',
            old_name='BusinessEntityID',
            new_name='CustomerGeographyID',
        ),
    ]
